"""empty message

Revision ID: 009990be25e2
Revises: b33e1a658211
Create Date: 2024-10-18 15:30:49.702731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009990be25e2'
down_revision = 'b33e1a658211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('e_mail', sa.String(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('NewsCards', schema=None) as batch_op:
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NewsCards', schema=None) as batch_op:
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('e_mail')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
