"""empty message

Revision ID: 0b5006e6eb3a
Revises: 6fd27f6245da
Create Date: 2024-10-18 05:10:14.446824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5006e6eb3a'
down_revision = '6fd27f6245da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('e_mail', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['e_mail'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('e_mail')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
