"""empty message

Revision ID: 1b1e647b7c7e
Revises: 998901780d0c
Create Date: 2024-10-26 09:37:15.090363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1e647b7c7e'
down_revision = '998901780d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
