"""empty message

Revision ID: 27a1081c2876
Revises: 2a041ba2ea8c
Create Date: 2024-11-26 05:19:37.981506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a1081c2876'
down_revision = '2a041ba2ea8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###
