"""empty message

Revision ID: 46aab575cd31
Revises: f696400303bd
Create Date: 2024-11-16 07:17:19.274413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aab575cd31'
down_revision = 'f696400303bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
