"""empty message

Revision ID: 4a5d6564fabb
Revises: b392130c381a
Create Date: 2024-12-18 15:11:57.541116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5d6564fabb'
down_revision = 'b392130c381a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
