"""empty message

Revision ID: 4f6b0567c156
Revises: 55ff291eb664
Create Date: 2024-11-01 19:27:07.709552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6b0567c156'
down_revision = '55ff291eb664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NewsCards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.String(), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NewsCards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
