"""empty message

Revision ID: 55ff291eb664
Revises: 1b1e647b7c7e
Create Date: 2024-10-26 09:38:18.479219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ff291eb664'
down_revision = '1b1e647b7c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
