"""empty message

Revision ID: 63f23e3119b3
Revises: f9e30f2359e0
Create Date: 2024-12-25 20:22:46.389726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f23e3119b3'
down_revision = 'f9e30f2359e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('imagepath', sa.String(length=200), nullable=True),
    sa.Column('imagepathbool', sa.Boolean(), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('KnowledgeBaseItems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KnowledgeBaseItems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('imagepath', sa.VARCHAR(), nullable=True),
    sa.Column('imagepathbool', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_creation', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('knowledge_base_items')
    # ### end Alembic commands ###
