"""empty message

Revision ID: 6b36d4d40935
Revises: cb90e61780f0
Create Date: 2024-11-18 07:13:36.320586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b36d4d40935'
down_revision = 'cb90e61780f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
