"""empty message

Revision ID: 8b57cb8ed198
Revises: 4a5d6564fabb
Create Date: 2024-12-18 15:12:37.229635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b57cb8ed198'
down_revision = '4a5d6564fabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_KnowledgeBaseItems')
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('_alembic_tmp_KnowledgeBaseItems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('imagepath', sa.VARCHAR(), nullable=True),
    sa.Column('imagepathbool', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_creation', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
