"""empty message

Revision ID: 998901780d0c
Revises: 009990be25e2
Create Date: 2024-10-18 15:32:57.746949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998901780d0c'
down_revision = '009990be25e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('e_mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('NewsCards', schema=None) as batch_op:
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('imagepath',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('tool_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('tool_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tool_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tool_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('NewsCards', schema=None) as batch_op:
        batch_op.alter_column('imagepath',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('e_mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
