"""empty message

Revision ID: b33e1a658211
Revises: 42058aa89671
Create Date: 2024-10-18 15:26:51.465976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33e1a658211'
down_revision = '42058aa89671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('e_mail', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin_Users', schema=None) as batch_op:
        batch_op.drop_column('e_mail')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
