"""empty message

Revision ID: b392130c381a
Revises: b456849bff17
Create Date: 2024-12-18 15:11:11.202170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b392130c381a'
down_revision = 'b456849bff17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_creation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.drop_column('date_of_creation')

    # ### end Alembic commands ###
