"""empty message

Revision ID: b456849bff17
Revises: e744cc22f4df
Create Date: 2024-12-18 15:10:08.381265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b456849bff17'
down_revision = 'e744cc22f4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_creation', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.drop_column('date_of_creation')

    # ### end Alembic commands ###
