"""empty message

Revision ID: c51ed0f00dee
Revises: 8b57cb8ed198
Create Date: 2024-12-18 15:14:19.803577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51ed0f00dee'
down_revision = '8b57cb8ed198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_KnowledgeBaseItems')
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=True)

    op.create_table('_alembic_tmp_KnowledgeBaseItems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('imagepath', sa.VARCHAR(), nullable=True),
    sa.Column('imagepathbool', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_creation', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
