"""empty message

Revision ID: cb90e61780f0
Revises: c0959040a022
Create Date: 2024-11-18 06:41:33.561353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb90e61780f0'
down_revision = 'c0959040a022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
