"""empty message

Revision ID: daa46e763214
Revises: 27a1081c2876
Create Date: 2024-12-03 08:26:21.227701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa46e763214'
down_revision = '27a1081c2876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagepathbool', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('endpointbool', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.drop_column('endpointbool')
        batch_op.drop_column('imagepathbool')

    # ### end Alembic commands ###
