"""empty message

Revision ID: e744cc22f4df
Revises: daa46e763214
Create Date: 2024-12-16 18:50:44.972179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e744cc22f4df'
down_revision = 'daa46e763214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.drop_column('endpoint')
        batch_op.drop_column('endpointbool')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpointbool', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('endpoint', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
