"""empty message

Revision ID: ee79d1325b80
Revises: c51ed0f00dee
Create Date: 2024-12-18 15:14:50.857132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee79d1325b80'
down_revision = 'c51ed0f00dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_KnowledgeBaseItems')
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_KnowledgeBaseItems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('imagepath', sa.VARCHAR(), nullable=True),
    sa.Column('imagepathbool', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_creation', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
