"""empty message

Revision ID: f696400303bd
Revises: 4f6b0567c156
Create Date: 2024-11-16 07:15:53.686060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f696400303bd'
down_revision = '4f6b0567c156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tool_Cards', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
