"""empty message

Revision ID: f9e30f2359e0
Revises: ee79d1325b80
Create Date: 2024-12-18 15:15:27.316440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e30f2359e0'
down_revision = 'ee79d1325b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KnowledgeBaseItems', schema=None) as batch_op:
        batch_op.alter_column('date_of_creation',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
